### ISSUE TITLE
response -> headers -> location sem o ID do author recém cadastrado.

### ISSUE THREAD

**Issue by regisfbrilhante** [e-cordel/ecordel-restapi#22]
Ao cadastrar um novo author, o location no headers não contém a localização completa do recurso recém cadastrado. Falta o ID no final da URL.
Teste realizado ao cadastrar um novo author e o respectivo response:

headers : {'Server': 'Cowboy', ... , 'Location': 'https://ecordel-restapi.herokuapp.com/authors/', ... , 'Date': 'Thu, 22 Jul 2021 13:44:45 GMT', 'Via': '1.1 vegur'}

**Comment by itsmemarioss** [comment]
Corrigido no pr #23
