### ISSUE TITLE
criar rota para author detail

### ISSUE THREAD

**Issue by regisfbrilhante** [e-cordel/ecordel-restapi#24]
Criar uma rota que responda com os detalhes de um autor. Ex.:  [host]/api/v1/authors/1

**Comment by halkernel** [comment]
tem alguém trabalhando já nisso @itsmemarioss , @karloskelvinsantos ?

**Comment by itsmemarioss** [comment]
Eu não estou, era bom criar uma issue no trello tbm?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
